/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as HelloRouteImport } from './routes/hello'
import { Route as RedisRouteImport } from './routes/redis'
import { Route as ApiShapesHelloWorldRouteImport } from './routes/api/shapes/hello-world'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const HelloRoute = HelloRouteImport.update({
  id: '/hello',
  path: '/hello',
  getParentRoute: () => rootRouteImport,
} as any)
const RedisRoute = RedisRouteImport.update({
  id: '/redis',
  path: '/redis',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShapesHelloWorldRoute = ApiShapesHelloWorldRouteImport.update({
  id: '/api/shapes/hello-world',
  path: '/api/shapes/hello-world',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/hello': typeof HelloRoute
  '/redis': typeof RedisRoute
  '/api/shapes/hello-world': typeof ApiShapesHelloWorldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/hello': typeof HelloRoute
  '/redis': typeof RedisRoute
  '/api/shapes/hello-world': typeof ApiShapesHelloWorldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/hello': typeof HelloRoute
  '/redis': typeof RedisRoute
  '/api/shapes/hello-world': typeof ApiShapesHelloWorldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/hello' | '/redis' | '/api/shapes/hello-world'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/hello' | '/redis' | '/api/shapes/hello-world'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/hello'
    | '/redis'
    | '/api/shapes/hello-world'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  HelloRoute: typeof HelloRoute
  RedisRoute: typeof RedisRoute
  ApiShapesHelloWorldRoute: typeof ApiShapesHelloWorldRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hello': {
      id: '/hello'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof HelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redis': {
      id: '/redis'
      path: '/redis'
      fullPath: '/redis'
      preLoaderRoute: typeof RedisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shapes/hello-world': {
      id: '/api/shapes/hello-world'
      path: '/api/shapes/hello-world'
      fullPath: '/api/shapes/hello-world'
      preLoaderRoute: typeof ApiShapesHelloWorldRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  HelloRoute: HelloRoute,
  RedisRoute: RedisRoute,
  ApiShapesHelloWorldRoute: ApiShapesHelloWorldRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/solid-start'
declare module '@tanstack/solid-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
